import Head from "next/head";
import Trending from "../../components/Trending";
import styles from "../../styles/Home.module.css";
import api, { endPoints } from "../../utils/api";
import Stories from "../../components/stories";
import Nav from "../../components/nav";

export default function StoriesPage({ data }) {
  const hero = data.find((item) => item.title === "Hero");
  const stories = data.find((item) => item.title === "Hero2");

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Trending data={hero} />
      <Stories data={stories.stories} />
    </div>
  );
}

export const getStaticProps = async () => {
  // const stories = await api.get("stories");
  const { data } = await api.get("/categories");

  return {
    props: { data },
    revalidate: 1,
  };
};
